<?php

/**
 * @file
 * Contains general.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function general_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.general':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('General') . '</p>';
      return $output;

    default:
  }
  return NULL;
}

/**
 * Implements hook_page_attachments().
 */
function general_page_attachments(array &$attachments) {

}
